### ISSUE TITLE
Reverted order for the site menu on mobile

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/rosa2#245]
A customer recently noticed that the order of the site menus is different on desktop vs. mobile. On desktop, Menu 1 is displayed first, on the left, and Menu 2 is placed secondly, at the right, which is correct. On mobile, instead, the first one is Menu2, and then comes Menu1. 

Is there a reason we did that, or it's just something we need to fix? 

Thank you. 

____
[Suppport Ticket](https://secure.helpscout.net/conversation/1483863403/55778/)

**Comment by madalingorbanescu** [comment]
Hey @georgeolaru,

Thank you for updating the order of the block on our demo, by doing that, all users were already getting the correct order. Now, I have also u[pdated the order](https://github.com/pixelgrade/nova-blocks/commit/58a029cf6a0e107853e868eaa8be231dd3f64eb9) for the single-row header, so when the user will add a new header block, it will use the correct order.
