### ISSUE TITLE
WooCommerce blocks styling from the editor not consistent with live website

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#261]
When I add any of the default WooCommerce editor blocks (Products by Category, Products by Tag, etc) in a page, the styling for the buttons and the product title is different than what I see on the front-end.

![CleanShot 2021-06-09 at 16 19 50](https://user-images.githubusercontent.com/53944294/121362160-93d07680-c93e-11eb-9548-91b7ff9c4775.png)

It seems like:

- [x] the font weight is overwritten to a value of 700 instead of 400
- [x] the buttons display with a different style than what's on the live website.

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/rosa2/commit/d097769201ace9aefb0f97ecf317f74bfe305af4
