### ISSUE TITLE
The Media card collection block looks wrong after trying to edit the paragraph as HTML 

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/rosa2#264]
When you try to edit the paragraph using the **Edit as HTML** option, it looks weird, I had a client who complained about it, but I don't know exactly why he did it or what caused him to switch to HTML. If you change the block, then it looks ok.

Here's a video to show you what I mean: 

https://user-images.githubusercontent.com/46753473/122360856-65b2ee00-cf5f-11eb-94f6-bb1b22b06416.mp4

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/nova-blocks/commit/b74f01e5f6558c1a0506c9e12ff4652df29bfe6d
