### ISSUE TITLE
The Map Disappears When Scrolling Down the Page 

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/rosa2#276]
When scrolling down the page where the Map block is used, the Map disappears too fast, I guess. 

https://user-images.githubusercontent.com/6790170/125277009-96493600-e319-11eb-9150-04963d7708a9.mp4

It happens only when the **Scrolling Effect** is set to **Parallax**

It can be tested on demo site, too, at https://demos.pixelgrade.com/rosa2/contact/.

**Comment by razwan** [comment]
Fixed in https://github.com/pixelgrade/nova-blocks/commit/33db62aea5ec5c5dad9a0dcd0534092c5c726946 - shipped with `Nova Blocks 1.12.4`
