### ISSUE TITLE
Improve Font Size Variation Control

### ISSUE THREAD

**Issue by georgeolaru** [pixelgrade/rosa2#281]
Let's explore a solution to use the Font Size option to "navigate" the type scale and set the Headings style based on a mix of Heading number + Font Size level, in which case an H3 with Larger (+1) font-size would look like an H2.

In Gutenberg, there are currently two modifiers in each direction:
- Smallest (-2)
- Smaller (-1)
- Normal (±0)
- Larger (+1)
- Largest (+2)

In Style Manager, here are fields that could be set:
- H6
- H5
- H4
- H3
- H2 (Secondary)
- H1 (Primary)

At the bottom of the type scale, I suggest not go below H6 size and make Smallest (-2) and Smaller (-1) look the same as H6. But on the top, we could add two more controls in Style Manager and use them with the Font Size control:
- Display (H1 + 1)
- Super Display (H1 + 2)

---
@razwan could you take a look over this and ping me if you want to discuss extra?

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/rosa2/pull/283
