### ISSUE TITLE
[WP 5.8] Small issue while trying to add new block to Widgets 

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/rosa2#285]
While testing Rosa2 with the new WordPress v5.8 and playing with the Widget Block editor, I noticed a small issue — when you want to add a new block by using the "+" sign from the top, you get this: 

<img width="1156" alt="CleanShot 2021-07-21 at 16 15 58@2x" src="https://user-images.githubusercontent.com/6790170/126494767-623b52db-5485-47a0-ada1-c3860eb1e7e0.png">

**Comment by madalingorbanescu** [comment]
The layout is handled by Sidecar's grid, which code is in Nova Blocks. I have made a [commit](4eea782904a2cfac4634ef42378d53e50700748a) there to address this issue. All good now👌
