### ISSUE TITLE
 Mobile menu links are darker after clicking a WooCommerce page.

### ISSUE THREAD

**Issue by Alexandru-Teodorescu** [pixelgrade/rosa2#286]
After the latest theme update, a user reported that the menu links from the mobile menu are darker after clicking a WooCommerce page.

I've tested on my local environment, and I can confirm that's true. Here's a video explanation:

https://user-images.githubusercontent.com/46753473/126745517-d8979b8d-2164-478c-9501-63a38535b09d.mp4

Ticket: https://secure.helpscout.net/conversation/1578068979/58555/

**Comment by madalingorbanescu** [comment]
This issue is related to how Nova Blocks is enqueueing or dequeuing styles. I am going to continue [here](https://github.com/pixelgrade/nova-blocks/issues/306) and close this issue.
