### ISSUE TITLE
List block show as broken in the editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#293]
After the latest updates to WP 5.8, Rosa2 1.12.4 and Nova Blocks 1.12.7, all already added List blocks have the following error next to them:

<img width="1280" alt="CleanShot 2021-07-27 at 14 58 27@2x" src="https://user-images.githubusercontent.com/53944294/127149813-8646aedc-af75-43ef-8690-118902a4dd1b.png">

Clicking _Attempt Block Recovery_ does the trick but maybe there's something we can do to avoid this from happening.

**Comment by madalingorbanescu** [comment]
In your screenshot, the message is different, however, while accessing the FlairScent website it looks that she is getting _Attempt Block Recovery_ notification.

As I was saying [here](https://github.com/pixelgrade/rosa2/issues/294#issuecomment-892627284), this is not really an issue, only a notification from the Editor that will inform the user about mark-up changes on blocks, and currently there is no way to avoid this.

**Comment by andreiungurianu** [comment]
Thanks for checking this issue and for the detailed explanation. I think this notification will be something our customers will encounter at various times during the process of improving Rosa2 and I think a documentation article that explains what happens is necessary.
