### ISSUE TITLE
Open table block shows as broken in the editor

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#294]
As experienced with two other blocks (see #293 and #292) the same is true for the Open Table block:

https://user-images.githubusercontent.com/53944294/127150389-82e3f2cf-658b-4527-9283-8b503da87fec.mp4

**Comment by madalingorbanescu** [comment]
The block is not broken, this is a message provided by the editor to announce user that the current block mark-up has been updated. In this case, there are new classes (`sm-palette-1 sm-variation-1`) added to the block, by using the Color Signal component.

In the front end, nothing is changed and the block works. If you will hit _Attempt Block Recovery_, the block will be updated to its latest mark-up and everything will work just fine.

PS: I have also updated the block on demos, so new users will get the new version of the block.
