### ISSUE TITLE
Active Menu Item underline missing

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#295]
After the latest updates in Rosa2, Nova and Style Manager the highlight underline usually displayed below the active menu item does not load anymore:

![CleanShot 2021-07-27 at 16 05 33](https://user-images.githubusercontent.com/53944294/127163843-650d85eb-838a-48ec-9807-ce300a0d4a37.png)

**Comment by madalingorbanescu** [comment]
Closed in https://github.com/pixelgrade/rosa2/commit/7d035df69a5bb1538b316f4c9bc3a535a0fbb1c5
