### ISSUE TITLE
Several Paragraph/Text formating options not working corectly

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/rosa2#298]
There are a few issues I discovered while trying to format text in a paragraph block (or in a list block).

1. **The Bold and Italic formating seem to cancel each other out** in the editor and on the live website.

https://user-images.githubusercontent.com/53944294/127280281-dc093368-c3fe-44c1-a8b0-244050701632.mp4

2. **The Headings do not display correctly in the editor** - there's a default size that shows up for all types of headings

https://user-images.githubusercontent.com/53944294/127280474-6dc4a661-7848-4a9e-a584-500bda75974c.mp4

3. [Might not big a big issue but worth checking] **There's a big space between the Quote or Pullquote author and the quote text** — in the live website there's no such spacing

![CleanShot 2021-07-28 at 10 21 22](https://user-images.githubusercontent.com/53944294/127281058-5366c74a-796c-4802-8076-d240fd2a17b2.png)

4. **Lead paragraph does not apply visually in the editor.** The only time the text changes size compared to other paragraphs is when I format it to Bold or Italic

https://user-images.githubusercontent.com/53944294/127281275-20a7aaa7-8ee6-40cb-8c14-274c732837a0.mp4

5. [Might be intended behaviour but worth checking] **Paragraph Text Drop Cap option not applying** in editor or live website

https://user-images.githubusercontent.com/53944294/127281567-0cae9373-8402-4f87-94a9-261cfcc09bd2.mp4

I'm using WP 5.8, Rosa2 1.12.4 and Nova Blocks 1.12.7

**Comment by madalingorbanescu** [comment]
I have fixed all of them, except  **Paragraph Text Drop Cap option not applying**. We never had any dropcap, so we will ignore it for now.
